[package]
name = "coins_on_the_clock"
version = "0.1.0"
authors = ["Mark Lodato <mark@gnar.dog>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
